# Declared in a Dockerfile so dependabot can watch for updates
# We won't get updates while we are using the :alpine tag, but hopefully we'll get versioning at some point
FROM nginxproxy/nginx-proxy:alpine
