version: 2
updates:
  - package-ecosystem: docker
    directory: acme-companion
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: nginx-proxy
    schedule:
      interval: weekly
