version: '2.4'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080:80"
      - "127.0.0.1:4433:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    network_mode: bridge

  letsencrypt:
    container_name: nginx-proxy-le
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
    network_mode: bridge

volumes:
  certs:
  conf:
  dhparam:
  html:
  vhost:
