version: '2.4'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    network_mode: bridge

  acme-companion:
    container_name: nginx-proxy-acme-companion
    build: acme-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    network_mode: bridge

volumes:
  acme:
  certs:
  conf:
  dhparam:
  html:
  vhost:
